### ISSUE TITLE
After Valheim 0.211.11 released, InstantEquip prevents me from joining a server.

### ISSUE THREAD

**Issue by MonolithTMA** [blaxxun-boop/InstantEquip#1]
I went through and tested all of my mods, and this was the one that prevented me from joining a server. It wasn't one I suspected since it doesn't seem to have anything to do with the server. It still works fine in solo play.

**Comment by blaxxun-boop** [comment]
Yes, all mods that sync their configs from the server broke with the update. They are slowly being updated, but I have like 90 mods that need to be updates, so please bear with me. I went ahead and updated InstantEquip now.

**Comment by MonolithTMA** [comment]
Thanks so much!
